# Site
name: "Yoshiki Noguchi BLOG"
title: "Yoshiki Noguchi BLOG"
description: "野口ブログ執筆中."
logo: "assets/images/cycling.jpeg"
favicon: "assets/images/cycling.jpeg"
baseurl: ""
google_analytics: "UA-46278016-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
future: true

# Authors
authors:
  Yoshiki:
    name: Yoshiki Noguchi
    display_name: Yoshiki Noguchi
    email: yoshiki.noguchi@dammy.co.jp
    description: "m1 student"
    avatar: "assets/images/cycling.jpeg"
# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
